# Generated by Django 5.2.4 on 2025-07-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_auction', '0004_alter_listings_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
